NEXT_PUBLIC_SITE_URL=https://arx-softwares.vercel.app/
NEXT_PUBLIC_IS_LIVE=true
NEXT_PUBLIC_IS_PRODUCTION=true
MONGODB_URI=mongodb://127.0.0.1:27017/
NEXT_PUBLIC_BASE_URL=http://localhost:3000
NEXT_PUBLIC_VISITORS_URL=/api/v1/visitors
COOKIE_NAME=ARX_SOFTWARES
ADMIN_EXPIRES_IN="30d"
JOSE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIF8b/xRAr9pnjNdVE3/gghHvRjdphHOu8MCQKsMh2PhK\n-----END PRIVATE KEY-----"
NEXT_PUBLIC_JOSE_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAot3T9cLuddzCq59cdRzTVlz0bQCCKDJLIVwCirZheYo=\n-----END PUBLIC KEY-----"
LAST_VISIT_TIMESTAMPS_COOKIENAME=LAST_VISIT
LAST_VISTI_TIMESTAMPS_TIME=600000
